# Generated by Django 4.0.5 on 2022-06-07 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_mlmodeltraining_dataset_mlmodeldataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('type', models.CharField(choices=[('binary', 'Binary'), ('number', 'Number'), ('category', 'Category'), ('bag', 'Bag'), ('sequence', 'Sequence'), ('vector', 'Vector'), ('audio', 'Audio'), ('date', 'Date'), ('h3', 'H3'), ('image', 'Image'), ('timeseries', 'Time Series')], max_length=1024, verbose_name='Type')),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InputFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('type', models.CharField(choices=[('binary', 'Binary'), ('number', 'Number'), ('category', 'Category'), ('bag', 'Bag'), ('sequence', 'Sequence'), ('vector', 'Vector'), ('audio', 'Audio'), ('date', 'Date'), ('h3', 'H3'), ('image', 'Image'), ('timeseries', 'Time Series')], max_length=1024, verbose_name='Type')),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.mlmodel')),
            ],
        ),
    ]
