# Generated by Django 4.0.5 on 2022-06-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_outputfeatures_inputfeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfeatures',
            name='models',
        ),
        migrations.AddField(
            model_name='outputfeatures',
            name='model',
            field=models.ForeignKey(default='26377c1d-4aa3-4e78-b502-e438095cc5a2', on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='training.mlmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputfeatures',
            name='models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='training.mlmodel'),
        ),
    ]
