# Generated by Django 4.0.5 on 2022-06-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_outputfeatures_models_outputfeatures_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputfeatures',
            old_name='models',
            new_name='model',
        ),
    ]
