# Generated by Django 4.0.5 on 2022-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_mlmodelversion_dataset_mlmodelversion_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelversion',
            name='trained',
            field=models.DateTimeField(blank=None, editable=False, null=None),
        ),
    ]
