# Generated by Django 4.0.5 on 2022-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_mlmodelversion_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelversion',
            name='trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
