# Generated by Django 4.0.5 on 2022-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_mlmodelversion_bucket_alter_mlmodelversion_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelversion',
            name='bucket',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='bucket',
            field=models.CharField(default='61ed1654-c518-4d09-a7b4-c76758ed1b14', max_length=1024, verbose_name='Bucket'),
            preserve_default=False,
        ),
    ]
