# Generated by Django 4.0.5 on 2022-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_mlmodelversion_bucket_mlmodel_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelversion',
            name='status',
            field=models.CharField(choices=[('wait', 'Wait to start'), ('training', 'Training'), ('error', 'Error'), ('finished', 'Finished')], default='finished', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
